[package]
name = "ticket_master"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.2"
openzeppelin_token = "2.0.0"
openzeppelin_access = "2.0.0"
openzeppelin_macros = "2.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis.git" }
ekubo_oracle_extension = { git = "https://github.com/EkuboProtocol/oracle-extension.git", tag = "v1.1.0" }

[dev-dependencies]
snforge_std = "0.49.0"
assert_macros = "2.12.2"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

# Visit https://foundry-rs.github.io/starknet-foundry/appendix/scarb-toml.html for more information

# [tool.snforge]
exit_first = true
fuzzer_runs = 1000
fuzzer_seed = 1

[[tool.snforge.fork]]
name = "mainnet"
url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "sepolia"
url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_9"
block_id.tag = "latest"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

# [features]                                                 # Used for conditional compilation
# enable_for_tests = []                                      # Feature name and list of other features that should be enabled with it
